params = {
    "beta": 0.95,
    "rho": 2,
    "lambda": 1,
    "sigma": 1,
    "interest_rate": 0.04,
    "utility_leisure_constant": 2,
    "utility_leisure_age": 1,
    "disutility_part_time": -2,
    "disutility_full_time": -4,
    # caregiving
    "utility_informal_care_parent_medium_health": 2,
    "utility_informal_care_parent_bad_health": 1,
    "utility_formal_care_parent_medium_health": 0.7,
    "utility_formal_care_parent_bad_health": 1,
    "utility_combination_care_parent_medium_health": -0.8,
    "utility_combination_care_parent_bad_health": -1.5,
    # caregiving if sibling present
    "utility_informal_care_medium_health_sibling": 2.5,
    "utility_informal_care_bad_health_sibling": 2,
    "utility_formal_care_medium_health_sibling": 1,
    "utility_formal_care_bad_health_sibling": 1,
    "utility_combination_care_medium_health_sibling": -0.2,
    "utility_combination_care_bad_health_sibling": -0.4,
}
